// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5V4RqBroAbyw_9HWXfGEYnn_cNivS-Uo',
    appId: '1:889290311173:web:fd82f015254674561afe6c',
    messagingSenderId: '889290311173',
    projectId: 'kawoa-a3e1f',
    authDomain: 'kawoa-a3e1f.firebaseapp.com',
    databaseURL: 'https://kawoa-a3e1f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kawoa-a3e1f.appspot.com',
    measurementId: 'G-G3R7VBZCBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp5iMyVoNwKzLyn0LS9r0fhnX735CBIPU',
    appId: '1:889290311173:android:626d3358e7a426661afe6c',
    messagingSenderId: '889290311173',
    projectId: 'kawoa-a3e1f',
    databaseURL: 'https://kawoa-a3e1f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kawoa-a3e1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiMihGG-wtoKLeuexo_UgAOX8TNrMmEOY',
    appId: '1:889290311173:ios:db7355632a121a101afe6c',
    messagingSenderId: '889290311173',
    projectId: 'kawoa-a3e1f',
    databaseURL: 'https://kawoa-a3e1f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kawoa-a3e1f.appspot.com',
    iosBundleId: 'com.example.projet',
  );
}
